; RNK skin downloads
materials/models/player/czero/gign_body_c.vmt
materials/models/player/czero/gign_body_col.vtf
materials/models/player/czero/gign_body_nml.vtf
materials/models/player/czero/gign_head_col.vmt
materials/models/player/czero/gign_head_col.vtf
materials/models/player/czero/gign_head_nml.vtf
materials/models/player/czero/leet_body_c.vmt
materials/models/player/czero/leet_body_col.vtf
materials/models/player/czero/leet_body_nml.vtf
materials/models/player/czero/leet_head_col.vmt
materials/models/player/czero/leet_head_col.vtf
materials/models/player/czero/leet_head_nml.vtf
materials/models/weapons/v_models/csgohands/ct_arms.vmt
materials/models/weapons/v_models/csgohands/ct_arms.vtf
materials/models/weapons/v_models/csgohands/ct_arms_normal.vtf
materials/models/weapons/v_models/csgo_ak47/ak47.vmt
materials/models/weapons/v_models/csgo_ak47/ak47.vtf
materials/models/weapons/v_models/csgo_ak47/ak47_exponent.vtf
materials/models/weapons/v_models/csgo_awp/awp.vmt
materials/models/weapons/v_models/csgo_awp/awp.vtf
materials/models/weapons/v_models/csgo_awp/awp_exponent.vtf
materials/models/weapons/v_models/csgo_awp/scope.vtf
materials/models/weapons/v_models/csgo_awp/scope_awp.vmt
materials/models/weapons/v_models/csgo_awp/scope_normal.vtf
materials/models/weapons/v_models/rif_m4a1/normal.vtf
materials/models/weapons/v_models/rif_m4a1/rif_m4a1.vmt
materials/models/weapons/w_models/w_rif_m4a1/rif_m4a1.vmt
materials/models/weapons/v_models/arms/ct_arms_fbi.vtf
materials/models/weapons/v_models/arms/ct_arms_idf.vmt
materials/models/weapons/v_models/arms/ct_arms_normal.vtf
materials/models/weapons/v_models/arms/ct_arms_st6.vtf
materials/models/weapons/v_models/knife_tactical/knife_tactical.vmt
materials/models/weapons/v_models/knife_tactical/knife_tactical.vtf
materials/models/weapons/v_models/knife_tactical/knife_tactical_exponent.vtf
materials/models/weapons/v_models/knife_tactical/knife_tactical_normall.vtf
